/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 bmw.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bmw.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-286.371, 0, 164.751]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.Meshesinterior71Mtl} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Meshespillars1Mtl} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Meshespillars1Mtl} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Meshesheadlight51Mtl} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Mesheslogo11Mtl} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Meshesdash11Mtl} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Mesheschrome51Mtl} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Meshesredlight1Mtl} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Meshesinterior231Mtl} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Meshesinterior181Mtl} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Mesheslight51Mtl} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Meshesengine51Mtl} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Meshesled11Mtl} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Meshesbody151Mtl} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Meshesblack151Mtl} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Mesheswindows1Mtl} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Mesheslogo31Mtl} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Meshesled111Mtl} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Mesheslivery1Mtl} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Meshestail71Mtl} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Meshesff41Mtl} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Meshesblack161Mtl} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Meshespiggrill1Mtl} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Mesheszx1Mtl} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Mesheszx1Mtl} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Mesheswhite41Mtl} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Meshesraidiator1Mtl} />
      </group>
      <group position={[-286.371, 0, 164.751]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_32.geometry} material={materials.Caliper1Mtl} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Meshesm8rim1Mtl} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Meshesm8rim0011Mtl} />
      </group>
      <mesh geometry={nodes.Object_100.geometry} material={materials['Material.001']} position={[-0.761, 5.655, -9.948]} scale={[3.715, 0.058, 0.668]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials['Material.003']} position={[1.812, 5.035, -9.638]} scale={[0.085, 0.794, 0.566]} />
      <mesh geometry={nodes.Object_101.geometry} material={materials['Material.003']} position={[-3.461, 4.912, -9.742]} scale={[0.085, 0.717, 0.584]} />
    </group>
  )
}

useGLTF.preload('/bmw.glb')
